# Generated by Django 5.0 on 2024-01-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='ip',
            new_name='ip_address',
        ),
    ]
