# Generated by Django 5.0 on 2023-12-20 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
