# Generated by Django 5.0 on 2023-12-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
