# Generated by Django 5.0 on 2024-01-13 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_rename_ip_reviewrating_ip_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
