# Generated by Django 5.0 on 2024-02-10 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_useraddress_remove_userprofile_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address_line_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='INDIA', max_length=50),
        ),
    ]
