# Generated by Django 5.0 on 2023-12-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_short_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_short_desc',
        ),
    ]
