# Generated by Django 5.0 on 2023-12-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productgallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='original_price',
        ),
    ]
