# Generated by Django 5.0 on 2024-01-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_reviewrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewRating',
        ),
    ]
